Add support for schema generation
flix-tech/avro-serde-php pull request #37
Opened 2020-10-12 13:56 UTC by fcoedno

## Overview

This PR adds up to my [last one](https://github.com/flix-tech/avro-serde-php/pull/35) by enabling us to generate schemas from class metadata.

I've also defined two interfaces: SchemaAttributeReader and SchemaAttribute. The goal here is to enable the support for [php8 attributes](https://wiki.php.net/rfc/attributes_v2) in the future.

It supports complex types, logical types and primitive types. It also supports defining nested records. Here a sample usage:

```php
<?php

use FlixTech\AvroSerializer\Objects\DefaultSchemaGeneratorFactory;
use FlixTech\AvroSerializer\Objects\Schema\Generation\Annotations as SerDe;

/**
 * @SerDe\AvroType("record")
 * @SerDe\AvroName("user")
 */
class User
{
    /**
     * @SerDe\AvroType("string")
     * @var string
     */
    private $firstName;

    /**
     * @SerDe\AvroType("string")
     * @var string
     */
    private $lastName;

    /**
     * @SerDe\AvroType("int")
     * @var int
     */
    private $age;

    public function __construct(string $firstName, string $lastName, int $age)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->age = $age;
    }

    public function getFirstName(): string
    {
        return $this->firstName;
    }

    public function getLastName(): string
    {
        return $this->lastName;
    }

    public function getAge(): int
    {
        return $this->age;
    }
}

$generator = DefaultSchemaGeneratorFactory::get();

$schema = $generator->generate(User::class);
$avroSchema = $schema->parse();
```

Further examples can be seen in the test cases.

## Improvements

Here a list of possible future improvements:

 * Infer field types from class type annotations and/or type hints (php 7.4). Today, we need to be explicit about the types of each field, which can be a little redudant sometimes.
 * Add support for php8 attributes.

2020-10-12 14:36 UTC, fcoedno commented
I will make the same request as before, if possible, please add the _hacktoberfest-accepted_ label to the PR

2020-10-16 08:08 UTC, tPl0ch requested changes
Hey, thanks so much for your contributions! They are really appreciated! :+1: 

I have some minor nits regarding the usage of constants over raw strings, since we would re-use these strings in multiple places.

2020-10-16 08:08 UTC, tPl0ch commented on src/Objects/Schema/Generation/SchemaAttributes.php
> +        return $this->attributes['type'] ?? [];
Nit: We could now use the `type` constant here instead of a hard coded string

2020-10-16 08:08 UTC, tPl0ch commented on src/Objects/Schema/Generation/SchemaAttributes.php
> +        if ('type' !== $attribute->avroName()) {
Nit: We could now use the `type` constant here instead of a hard coded string

2020-10-16 08:08 UTC, tPl0ch commented on src/Objects/Schema/Generation/SchemaGenerator.php
> +        }
Nit: These strings could also be replaced by the constants

2020-10-16 08:08 UTC, tPl0ch commented on src/Objects/Schema/Generation/SchemaGenerator.php
> +                return $this->applyAttributes($schema, $attributes);
Nit: These could all be checks against the constants

2020-10-16 08:08 UTC, tPl0ch commented on src/Objects/Schema/Generation/SchemaGenerator.php
> +
Nit: These could all be checks against the constants

2020-10-16 13:52 UTC, tPl0ch approved these changes
LGTM

2020-10-16 13:54 UTC, fcoedno commented
@tPl0ch Not sure if you realized, but I had pushed other refactorings. It was about making use of the constants in the Schema classes. Did you manage to see those before merging?

2020-10-16 13:58 UTC, tPl0ch approved these changes
LGTM too 😸

2020-10-16 15:59 UTC, merged