Improve symfony/serializer integration
flix-tech/avro-serde-php pull request #44
Opened 2020-10-26 14:57 UTC by fcoedno

When serializing or deserializing objects, the property names may differ from the schema defined names. One option to overcome this issue is by using custom serializer annotations in the class properties.

However, since we have the Schema Generation feature that allows us to generate schema definition from class metadata, it seems to make sense to use the very same information to convert the names between the class property and the ones defined in the avro schema.

So, in this PR I create a NameConverter class, to be used with the serializer component, that does just that.

I messed up my last PR (#43) commits so I've created this new one.

2020-11-15 19:30 UTC, tPl0ch commented
@fcoedno I think this PR needs to be updated to run against the new PHPUnit API, since the latest release we only support PHPUnit 8.2.3 and above - due to PHP8 support.

2020-11-16 20:50 UTC, fcoedno commented
@tPl0ch well noted, thanks. I've fixed the issues.

2020-11-17 09:46 UTC, tPl0ch requested changes
Thanks again for your work, much appreciated! 👍

2020-11-17 09:46 UTC, tPl0ch commented on test/Integrations/Symfony/Serializer/AvroNameConverterTest.php
> +            new AnnotationReader(new \Doctrine\Common\Annotations\AnnotationReader())
Nit: Please import the namespaces

2020-11-17 22:45 UTC, tPl0ch approved these changes
Thanks again for this contribution @fcoedno !

2020-11-17 22:46 UTC, merged